### ISSUE TITLE
Can not choose language during installation

### ISSUE THREAD

**Issue by anthonyherve** [vinkla/wordplate#339]
Hello,

It's first time I use Wordplate.
I follow instructions and use command "composer create-project --prefer-dist vinkla/wordplate altea"  to create my project.
It installed version 12.4.2 because I use PHP 8.0.
WXhen I go to my local website, I'm directly on this page
![image](https://user-images.githubusercontent.com/1899492/216353792-c198f7e7-ecf6-4025-aed5-d98ae597c261.png)

And I can not choose language as usually.
I do installation of WordPrss and in Settings > General, I have only English language.
I have tried to follow tutorials to add .mo files into a new wp-content/languages directory but without success.

Can you help me please?

Thank you in advance.

**Comment by vinkla** [comment]
I recommend using this project to install languages using Composer: https://wp-languages.github.io/

**Comment by anthonyherve** [comment]
Thank you for your quick answer. I have installed my french package with https://wp-languages.github.io/. It's very convenient.
But I have the same problem. I have always only English language in Settings > General. And I don't understand why I can't choose language when I install Wordpress after installing Wordplate.
Maybe I forget some steps.

Can you please help me?

**Comment by vinkla** [comment]
Sorry, can't help you debug your application. If you think this is because of WordPlate, please submit a pull request.

**Comment by kskrlinnorth2** [comment]
For anyone having this same issue, if you see just `English (United States)` language under `Settings - General - Site Language`, put this line in your .env file:

`DISALLOW_FILE_MODS=false`

Once you add your desired language, remove it from .env to disallow additional updates.
After that you will have the option to switch between those languages you added while DISALLOW_FILE_MODS was disabled.

For example, if you add german language and then remove this rule from .env, you will have dropdown with `English` and `German` language. This will also enable language dropdown at user level (which was missing while only english was available).

**Comment by botmaster** [comment]
> Thank you for your quick answer. I have installed my french package with https://wp-languages.github.io/. It's very convenient. But I have the same problem. I have always only English language in Settings > General. ![image](https://user-images.githubusercontent.com/1899492/216382236-4f4b97ae-4cac-4d65-88ef-d07b0d10b721.png)
> 
> And I don't understand why I can't choose language when I install Wordpress after installing Wordplate. Maybe I forget some steps.
> 
> Can you please help me?

Hello @anthonyherve 
Did you find a solution?
