### ISSUE TITLE
Bunch of deprecations after fresh installation

### ISSUE THREAD

**Issue by smartmeerkat** [vinkla/wordplate#349]
<details>
<summary>What I have immediately after installation:</summary>

![localhost_wordpress_wp-login php](https://user-images.githubusercontent.com/93769188/221993643-536e57e7-e32e-4bb5-999f-ed57f9415db7.png)

</details>

<details>
<summary>After log in:</summary>

![localhost_wordpress_wp-admin_](https://user-images.githubusercontent.com/93769188/221994317-b8336464-7d91-4f64-abfe-8c65815d529a.png)

</details>

I followed steps from README.md.

PHP 8.1
MariaDB 10.11.2.

**Comment by vinkla** [comment]
This is correct, sadly WordPress only has [beta support](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) for PHP 8.0, 8.1 and 8.2.

- [WordPress PHP 8.1 Support: Not Found](https://roots.io/wordpress-php-8-1-support-not-found/)
- [PHP in 2023](https://stitcher.io/blog/php-in-2023#the-ecosystem)
