### ISSUE TITLE
Activate ACF Show in REST API with wordplate ?

### ISSUE THREAD

**Issue by steve-ref** [vinkla/wordplate#426]
Hi, there, 
I've just taken over a project for my work that was done with Wordplate, which I don't know at all.
I need to be able to retrieve the ACF chamsp via the Wordpress api but I don't have the option in the Wordpress dashboard as is usually the case. Is there any way of doing this?

Regards,

Steve

**Comment by steve-ref** [comment]
Well...
It's not really the kind of answer I was expecting.

Normally I should be able to have this code structure :

`
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_65d314a11e8d3',
	[... all the field group attributes]
	'show_in_rest' => 1,
) );
} );
`

But I can't see anywhere where it's declared like that.
Even functions.php isn't in the available files

**Comment by steve-ref** [comment]
@fiskhandlarn 
Actually, I don't think I understand how ACF works with Wordplate.

If I understand correctly, to create my blocks, I need to call upon the different PHP files present in the Wordplate folder (for example: WysiwygEditor.php).

This means that in the project I've been assigned, I end up with a line of code like this: WysiwygEditor::make('something', 'something').

My question was whether there is a resource available for enabling the "Show in REST API" option for Wordplate because I don't have access to the user interface to do it in my WordPress admin with Wordplate (it works fine with another installation).

On a fresh WordPress installation with ACF PRO, I can either create my ACF fields and activate "Show In REST API" via the user interface or through functions.php, but I don't have access to either method with Wordplate (I don't have a functions.php, nor a checkbox in the admin).

Sorry for all these questions, I'm just trying to understand how it works.

**Comment by steve-ref** [comment]
@fiskhandlarn 

> i think they work just fine together. :)

Oh well yeah, It's me who doesn't understand how it works ^^, this is not a package problem, didn't want to offense.

Indeed, you're right, it's an outdated version of ExtendedACF but the imports are from Wordplate so I thought it was related to Wordplate itself.

My other question was:

I usually put functions in functions.php because that's what I've always been told. Where could I put this function without that file and without breaking the current code?

Thanks for your help

**Comment by fiskhandlarn** [comment]
> I usually put functions in functions.php because that's what I've always been told. Where could I put this function without that file and without breaking the current code?

anywhere you like, as long as you include/require it from `functions.php`. if you don't have a `functions.php` file present in your theme i suggest you create it. if you can't create it, i can't think of another way besides creating a plugin.
