### ISSUE TITLE
Dotenv and vite should be devDwpendencies

### ISSUE THREAD

**Issue by hirasso** [vinkla/wordplate#454]
Hi there! I was just skimming this very nice repo and noticed that both dotenv as well as vite should be `devDependencies` instead of `dependencies`.

Btw what do you prefer when contributing: Direct PRs or always an issue, first? :)

**Comment by vinkla** [comment]
Hi Rasso, I'm glad you like the project 🙌  

The `dotenv` and `vite` packages are required to build the project. The necessary setup depends on whether the assets are built on the server or locally. Personally, I add packages like `prettier` and `eslint` to `devDependencies` - packages I don't need when deploying the project from GitHub Actions.

**Comment by hirasso** [comment]
Ah, interesting! I usually have everything build-related in my devDependencies, while only bundled libraries make it into dependencies. The reason is that I often have to backport my current build process to older projects of mine and that convention makes it easy by being able to blindly copy the full devDependencies over.

Anyways, no biggie :)
