### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by CyrilBellamy** [vinkla/wordplate#455]
Hi,

I have created a fresh wordplate project andh i have install french language with 'koodimonni-language/fr_fr'.
Then, i have create a page with Gutenberg and the editor isn't fully translated.
I have also use wpcli for install but same result.
On another project, using older Wordplate version i don't have problem

![image](https://github.com/user-attachments/assets/314a1f9e-9142-43ac-acc2-7d28c55a3abc)
![image](https://github.com/user-attachments/assets/bf95ae93-f654-45eb-bc4d-facd6e853ba2)

**Comment by vinkla** [comment]
I don't think this is related to WordPlate. Can you reproduce this in a normal WordPress installation?

**Comment by CyrilBellamy** [comment]
When i disabled Gutenberg (**add_filter('use_block_editor_for_post', '__return_false');**)
![image](https://github.com/user-attachments/assets/bf479364-7183-47c4-96aa-81bc0e230476)

With
![image](https://github.com/user-attachments/assets/8f9c089a-704d-4b93-9f79-ab4542748622)

**Comment by vinkla** [comment]
If you find any bugs, please submit a pull request with a fix. For future GitHub issues, I recommend providing as much information as possible. This is an open-source community, not a support forum.
