### ISSUE TITLE
You should add this constant imho

### ISSUE THREAD

**Issue by mookseurosystemes** [vinkla/wordplate#462]
Hi,

You should add this constant IMHO in order to get rid of new default themes installations (twenty sixteen, twenty seventeen...) which are installed when a new major version of WP is released.

define('CORE_UPGRADE_SKIP_NEW_BUNDLED',env('DISABLE_BUNDLED', true));

Regards.

**Comment by vinkla** [comment]
Interesting, haven't read about this constant before. Do you have links to the documentation?

**Comment by mookseurosystemes** [comment]
Nothing in the Codex, but this was mentionned in the core track here, at line 807/810 : https://core.trac.wordpress.org/browser/tags/5.3/src/wp-admin/includes/update-core.php#L810

**Comment by vinkla** [comment]
I wonder if this makes any difference since we aren't allowing files to be edited from the dashboard.

**Comment by vinkla** [comment]
I tried it locally, and since we have `DISALLOW_FILE_MODS` set to `true` by default, this constant won't make any difference. 

Thank you for bringing it to our attention.
