### ISSUE TITLE
Manage plugins in the admin dashboard

### ISSUE THREAD

**Issue by hbeqi** [vinkla/wordplate#483]
Hi!

I am here with a bit of a weird question, but is it possible to mannage plugins from the admin dashboard? And when i say manage, i mean full management, like installing new ones, deleteting existing ones and so on, basically full on management as you would understand from a fresh wordpress installation without wordplate.

If such a thing is possible, can anyone explain to me how it can be done?

**Comment by vinkla** [comment]
Since we manage plugins and themes with Composer, there is no need to install plugins via the dashboard. This feature has been disabled for security reasons by using the `DISALLOW_FILE_MODS` constant. You can enable this behavior by setting it to `false` in your environment file.

**Comment by hbeqi** [comment]
Thanks so much for your answer
